# **1. Set**
- 수학의 집합과 비슷한 형태로 순서가 없기 때문에 어떤 값이 먼저 나올지 알 수 없고, 중복되는 데이터를 허용하지 않음
- 딕셔너리처럼 중괄호를 사용해서 선언하지만 key는 존재하지 않고 value만 존재

### 1-1. set 만들기

In [5]:
s1 = {1,3,5,7}
print(type(s1))

s2 = set([1,3,5,7])
print(type(s2))

s3 = {1,3,5,7,9,3,5,4,6,1,2}
print(s3)

<class 'set'>
<class 'set'>
{1, 2, 3, 4, 5, 6, 7, 9}

In [9]:
# 해당 세트에 2가 들어가있니? 응! True
print(2 in s3)
print(10 in s3)

# 해당 세트에 2가 없지? 아니! 있어! False
print(2 not in s3)

True
False
False

### 1-2. set 함수

In [16]:
# add() : set에 단일 데이터를 추가
s1 = {100, 200}
s1.add(150)
print(s1) # 순서 없음! 순서가 일정하지 않게 나옵니다!

# update() : set에 여러 데이터를 한 번에 추가
s2 = {10, 20, 30}
s2.update([40, 50, 60, 20])
print(s2)

# remove() : set의 데이터를 제거, 제거할 데이터가 없으면 에러!
s2.remove(50)
print(s2)
# s2.remove(50) 삭제할 데이터가 없다면 에러!

# discard() : set의 데이터를 제거, 제거할 데이터가 없어도 에러가 발생하지 않는다.
s2.discard(30)
print(s2)
s2.discard(30) # 삭제할 데이터가 없다 하더라도 아무 일도 일어나지 않는다.
print(s2)

{200, 100, 150}
{40, 10, 50, 20, 60, 30}
{40, 10, 20, 60, 30}
{40, 10, 20, 60}
{40, 10, 20, 60}

### 1-3. set 연산자

In [25]:
s1 = {10,20,30,40,50}
s2 = {30,40,50,60,70}

# 합집합
result = s1 | s2
print(result)
result = s1.union(s2)
print(result)

# 교집합
result = s1 & s2
print(result)
result = s1.intersection(s2)
print(result)

# 차집합
result = s1 - s2
print(result)
result = s2.difference(s1)
print(result)

# 대칭 차집합
result = s1 ^ s2
print(result)
result = s1.symmetric_difference(s2)
print(result)

{70, 40, 10, 50, 20, 60, 30}
{70, 40, 10, 50, 20, 60, 30}
{40, 50, 30}
{40, 50, 30}
{10, 20}
{60, 70}
{20, 70, 10, 60}
{20, 70, 10, 60}